
  version: "3.9" #version of docker-compose
  services:
    db:
      container_name: db
      image: mysql:8.0.1
      ports:
      - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=ripetizioni
        - MYSQL_USER=admin
        - MYSQL_PASSWORD=admin1

      volumes:
        - ./data:/var/lib/mysql                         #database data volume
        - ./src/main/db:/docker-entrypoint-initdb.d  #database files called when the container is built and started for the first time

# Da capire come automatizzare
#      command:
#        - msyql -u root -proot root
#        - CREATE USER 'admin'@'%' IDENTIFIED BY 'admin1';
#        - grant all on *.* to 'admin'@'%';

    web:
      container_name: tomcat
      build: .
      ports:
        - "8080:8080"
      links:
        - db
